# Generated by Django 6.0.5 on 2026-06-21 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cooked_food', 'Cooked Food'), ('raw_ingredients', 'Raw Ingredients / Groceries'), ('packaged_food', 'Packaged Food'), ('clothes', 'Clothes'), ('other', 'Other Resources')], default='cooked_food', max_length=20)),
                ('quantity', models.CharField(help_text="e.g. '20 plates', '15 kg'", max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('pickup_address', models.CharField(max_length=255)),
                ('expiry_time', models.DateTimeField(help_text='When this donation is no longer usable')),
                ('status', models.CharField(choices=[('pending', 'Pending (Unclaimed)'), ('claimed', 'Claimed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('claimed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ngo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_listings', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending (Unclaimed)'), ('claimed', 'Claimed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('expired', 'Expired')], max_length=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_updates', to='listings.listing')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
